
server:
  port: 9004
  servlet:
    context-path: '/remedios-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${remediosDBHost}:5432/${remediosDBBase}
    username: ${remediosDBUser}
    password: ${remediosDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_prefix: 
            audit_table_suffix: _auditoria
            revision_field_name: revisao
            revision_type_field_name: tipo
            store_data_at_delete: true
            default_schema: auditoria
