
server:
  port: 9003

spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: ${kafkaHost}:9092
  mail:
    host: ${emailHost}
    port: 587
    username: ${emailUser}
    password: ${emailPass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true